name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run SQLFluff
        run: uv run sqlfluff lint --format github-annotation-native

      - name: Run yamllint
        run: uv run yamllint .
