name: "{{ cookiecutter.project_slug }}"
version: "0.1.0"

profile: "{{ cookiecutter.project_slug }}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  materialized: view
